version: "3.9"
services:
  web:
    environment:
      - USERNAME=test
      - PASSWORD=12345
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "the_data_base:/db"
volumes:
  the_data_base:
    external: true
