version: "3.9"
services:
  web_1:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "the_data_base:/db"
  web_2:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - "the_data_base:/db"
  web_3:
    build: .
    ports:
      - "5002:5000"
    volumes:
      - "the_data_base:/db"

volumes:
  the_data_base:
    external: true
